language: bash

group: bluezone

dist: xenial

os: linux

sudo: required

matrix:
    include:
      - os: linux-ppc64le
      - os: linux-s390
        sudo: true

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D;
      echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" | sudo tee /etc/apt/sources.list.d/docker.list;
      sudo add-apt-repository -y ppa:webupd8team/java;
      echo "Killing auto-update to avoid lock conflicts";
      sudo systemctl stop apt-daily.service;
      sudo systemctl stop apt-daily.timer;
      ps aux | grep apt | grep -v grep | awk '{print $2}' | xargs sudo kill;
      echo "Running updates and installs";
      sudo apt-get update;
      echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections;
      sudo apt-get install -y oracle-java8-installer;
      sudo apt-get install -y docker-ce;
      sudo apt-get install -y oracle-java8-set-default;
    fi
  - if [ "$TRAVIS_OS_NAME" = "linux-s390" ]; then
      sudo apt-get install -y unzip wget;
    fi
  - sudo apt-get install -y dnsutils

script:
  - uname -a
  - cat /etc/issue
  - sudo docker-build/9.0.0.9/build $W3_USERNAME $W3_PASSWORD $IM_URL
